apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onlyoffice-ingress
  namespace: onlyoffice
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onlyoffice-documentserver
                port:
                  number: 80
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onlyoffice-api
                port:
                  number: 3000
    - host: {{ .Values.ingress.wsHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onlyoffice-editor
                port:
                  number: 8000

