apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documentserver-data-pvc
  namespace: onlyoffice
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize }}
  storageClassName: {{ .Values.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc
  namespace: onlyoffice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dbSize }}
  storageClassName: {{ .Values.persistence.dbStorageClass }}

